package com.assignment.libraryhibernate.entities;

// default package
// Generated Jan 14, 2019 8:11:46 AM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String username;
	private String password;
	private Boolean enabled;
	private Set authoritieses = new HashSet(0);

	public Users() {
	}

	public Users(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Users(String username, String password, Boolean enabled, Set authoritieses) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.authoritieses = authoritieses;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Set getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set authoritieses) {
		this.authoritieses = authoritieses;
	}

}
