package com.assignment.libraryspring.entities;
// default package
// Generated Dec 23, 2018 8:35:19 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8128804572167274877L;
	private Integer subjectId;
	private String subtitle;
	private int duration;
	private Set books = new HashSet(0);

	public Subject() {
	}

	public Subject(String subtitle, int duration) {
		this.subtitle = subtitle;
		this.duration = duration;
	}

	public Subject(String subtitle, int duration, Set books) {
		this.subtitle = subtitle;
		this.duration = duration;
		this.books = books;
	}

	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public Set getBooks() {
		return this.books;
	}

	public void setBooks(Set books) {
		this.books = books;
	}

	@Override
	public String toString() {
		return "subtitle: " + subtitle + "\ndurationInHours: " 
			+ duration + "\nsubjectId: " + subjectId;
	}
}
