package com.assignment.taskmanager.entities;

import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

// default package
// Generated Dec 23, 2018 8:35:19 PM by Hibernate Tools 5.2.10.Final

/**
 * Task generated by hbm2java
 */
public class ParentTask implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -1761563154699528174L;

	/**
	 * 
	 */
	private Integer parentId;
	
	private String parentTask;
	
	@JsonIgnore
	private Set<Task> tasks;


	public ParentTask() {
	}

	public ParentTask(Integer parentId, String parentTask,  Set<Task> tasks) {
		this.parentId = parentId;
		this.parentTask = parentTask;
		this.tasks = tasks;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getParentTask() {
		return parentTask;
	}

	public void setParentTask(String parentTask) {
		this.parentTask = parentTask;
	}

	@JsonIgnore
	public Set<Task> getTasks() {
		return tasks;
	}

	@JsonIgnore
	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}
	
	
	/*@Override
	public String toString() {
		return "title:" + title + "\nprice: " + price + "\nvolume: " + volume
				+ "\npublishDate: " + publishDate
				+ "\nbookId: " + bookId;
	}*/
}
