package com.assignment.taskmanager.entities;
// default package
// Generated Dec 23, 2018 8:35:19 PM by Hibernate Tools 5.2.10.Final

import java.util.Date;

import org.hibernate.validator.constraints.Range;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	
	private static final long serialVersionUID = -2368057243401337926L;
	/**
	 * 
	 */
	private Integer taskId;
	private Integer parentId;
	
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private ParentTask parentTask;
	private String task;
	private Date startDate;
	private Date endDate;
	
	@Range(min = 0, max = 30)
	private Integer priority;
	
	private Integer status;

	public Task() {
	}

	public Task(Integer taskId, Integer parentId, String task,
			Date startDate, Date endDate, Integer priority, Integer status) {
		this.taskId = taskId;
		this.parentId = parentId;
		this.task = task;
		this.startDate = startDate;
		this.endDate = endDate;
		this.priority = priority;
		this.status = status;
	}

	public Integer getTaskId() {
		return taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public String getTask() {
		return task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public ParentTask getParentTask() {
		return parentTask;
	}

	public void setParentTask(ParentTask parentTask) {
		this.parentTask = parentTask;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}	
	
	
	/*@Override
	public String toString() {
		return "title:" + title + "\nprice: " + price + "\nvolume: " + volume
				+ "\npublishDate: " + publishDate
				+ "\nbookId: " + bookId;
	}*/
}
